/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface BalenaHubFeedbackData {
	details?: string;
	[k: string]: unknown;
}

export interface BalenaHubFeedbackContractDefinition
	extends ContractDefinition<BalenaHubFeedbackData> {}

export interface BalenaHubFeedbackContract
	extends Contract<BalenaHubFeedbackData> {}
