/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type Username = string | null;
export type HowDidYouFirstHearAboutBalenaCloud = string;
export type HowWouldYouDescribeYourRole = string;
export type CouldYouBrieflyDescribeYourUseCase = string;
export type HowHasYourExperienceBeenSoFarWhatCanWeImproveWeCountOnYourHonestFeedbackToMakeBalenaCloudBetter =
	string;
export type HowLikelyAreYouToRecommendBalenaCloudToAFriendOrCoWorker = number;
export type CuratedOrigin = string[];
export type CuratedOriginDetail = string[];
export type CuratedRole = string[];
export type CuratedUseCaseSegment = string[];
export type CuratedUseCaseDetail = string[];
export type CuratedExperierienceEvaluation =
	| 'Very Positive'
	| 'Somewhat Positive'
	| 'Neutral'
	| 'Somewhat Negative'
	| 'Very Negative';
export type CuratedIssuesWants = string[];
export type CuratedHighlights = string[];
export type Status = 'open' | 'closed' | 'archived';

export interface TypeformFeedbackData {
	email?: string | null;
	user?: Username;
	howDidYouFirstHearAboutBalenaCloud?: HowDidYouFirstHearAboutBalenaCloud;
	howWouldYouDescribeYourRole?: HowWouldYouDescribeYourRole;
	couldYouBrieflyDescribeYourUsecase?: CouldYouBrieflyDescribeYourUseCase;
	howHasYourExperienceBeenSoFar?: HowHasYourExperienceBeenSoFarWhatCanWeImproveWeCountOnYourHonestFeedbackToMakeBalenaCloudBetter;
	howLikelyAreYouToRecommendBalenaCloud?: HowLikelyAreYouToRecommendBalenaCloudToAFriendOrCoWorker;
	curatedOrigin?: CuratedOrigin;
	originDetail?: CuratedOriginDetail;
	role?: CuratedRole;
	useCaseSegment?: CuratedUseCaseSegment;
	useCaseDetail?: CuratedUseCaseDetail;
	experienceEvaluation?: CuratedExperierienceEvaluation;
	issuesWants?: CuratedIssuesWants;
	highlights?: CuratedHighlights;
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	status: Status;
	[k: string]: unknown;
}

export interface TypeformFeedbackContractDefinition
	extends ContractDefinition<TypeformFeedbackData> {}

export interface TypeformFeedbackContract
	extends Contract<TypeformFeedbackData> {}
