/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface TypeformFeedbackData {
	[k: string]: unknown;
}

export interface TypeformFeedbackContractDefinition
	extends ContractDefinition<TypeformFeedbackData> {}

export interface TypeformFeedbackContract
	extends Contract<TypeformFeedbackData> {}
